INSERT INTO SupplyStore (SupplyID, BranchID, Location, Name) VALUES
(1, 1, 'New York', 'Tech Supplies Co.'),
(2, 2, 'Los Angeles', 'City Electronics'),
(3, 3, 'Chicago', 'Gadget World'),
(4, 4, 'Houston', 'Device Depot'),
(5, 5, 'Phoenix', 'Future Tech Supplies'),
(6, 6, 'Philadelphia', 'HomeTech Solutions'),
(7, 7, 'San Antonio', 'Pro Devices Store'),
(8, 8, 'San Diego', 'NextGen Electronics'),
(9, 9, 'Dallas', 'Techno Haven'),
(10, 10, 'San Jose', 'Supplies Plus'),
(11, 11, 'Austin', 'Innovative Electronics'),
(12, 12, 'Jacksonville', 'Tech Gadgets & More'),
(13, 13, 'Fort Worth', 'SmartTech Hub'),
(14, 14, 'Columbus', 'AllTech Supplies'),
(15, 15, 'Indianapolis', 'Best Devices Store'),
(16, 16, 'Charlotte', 'Tech Haven'),
(17, 17, 'Seattle', 'Tech Gear Co.'),
(18, 18, 'Denver', 'Supplies Express'),
(19, 19, 'Washington', 'Electro World'),
(20, 20, 'Boston', 'Gadget Central'),
(21, 21, 'El Paso', 'Device Kings'),
(22, 22, 'Nashville', 'Tech Unlimited'),
(23, 23, 'Detroit', 'Gadget Storehouse'),
(24, 24, 'Portland', 'FutureTech Supply'),
(25, 25, 'Memphis', 'Device Masters'),
(26, 26, 'Oklahoma City', 'Supplies Direct'),
(27, 27, 'Las Vegas', 'Gadget Empire'),
(28, 28, 'Louisville', 'Electronics Unlimited'),
(29, 29, 'Baltimore', 'Device Solutions'),
(30, 30, 'Milwaukee', 'TechMart');
